### PR TITLE
huihuihui

### PR DESCRIPTION
**Pull request by a9fm**

### CODE REVIEW

**Comment by Codwizer** [comment]
@dementr0n What's the point of adding a channel where there are few modules?

**Comment by coddrago** [comment]
@Codwizer согл кста.

**Comment by coddrago** [comment]
@dementr0n I add channels that have more than 5 modules, with the exception of autofarms, I add them if there are more than 15 of them.

**Comment by Codwizer** [comment]
@coddrago and it is also necessary, that the channel be beautifully decorated, and that there be no unnecessary garbage, in the channel, and without benches

**Pull request closed without merging**
